version: "3.9"

services:
  catalogdb:
    image: postgres:16
    container_name: catalogdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalogdb
    ports:
      - "9876:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  catalog.api:
    build: Services/Catalog/Catalog.API
    container_name: catalog_api
    depends_on:
      - catalogdb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      
      # Connection string per quando l'API gira in Docker
      ConnectionStrings__DefaultConnection: Host=catalogdb;Port=5432;Database=catalogdb;Username=postgres;Password=postgres
      
      #  Connection string alternativa per debug locale (Visual Studio su Windows)
      # Usa questa variabile solo in launchSettings.json o user-secrets
      ConnectionStrings__LocalConnection: Host=localhost;Port=9876;Database=catalogdb;Username=postgres;Password=postgres

    ports:
      - "8000:8080"
    restart: always

volumes:
  postgres_catalog:
